version: '3'
services:
  # PHP Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    tty: true
    working_dir: /var/www/api
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    volumes:
      - ./api:/var/www/api
      - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
      - redis
    networks:
      - app

  # Nginx Service
  nginx:
    image: nginx:alpine
    tty: true
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - ./api:/var/www/api
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
      - redis
    networks:
      - app

  # Node Service
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '5173:5173'
    volumes:
      - ./app:/var/www/app
      - /var/www/app/node_modules
    depends_on:
      - nginx
    networks:
      - app

  # MySQL Service
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: chagle
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    entrypoint:
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS chagle; CREATE DATABASE IF NOT EXISTS chagle_bot;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    networks:
      - app

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - app

  # Redis Service
  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    networks:
      - app

  # Mailhog Service
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - app

networks:
  app:
    driver: bridge